#!/bin/bash

kubectl delete \
    -f service1.yaml \
    -f service2.yaml \
	-f github.yaml \
	-f rebuild.yaml \
	-f secrets.yaml

rm -f cmds out

sed -i 's/text :=.*/text := "Hello World!"/' helloworld.go
git add helloworld.go && git commit -s -m "clean" && git push origin master 
make
