#!/bin/bash

set -e

TMPFILE=kapply-tmp${RANDOM}
CMD="apply"
OBJECT=""

if [[ "$1" == "-p" ]]; then
    CMD="patch"
	OBJECT="$2"
	shift 2
fi

while [[ -n "${1}" ]]; do
    file="${1}"
    shift

    rm -f "${TMPFILE}"
    IFS=''
    cat "${file}" | while read line ; do
        while [[ "$line" == *"\${"* && "$line" == *"}"* ]]; do
            pre=$(echo "$line" | sed "s/\([^\$]*\)\${\([^}]*\)}\(.*\)/\1/")
            var=$(echo "$line" | sed "s/\([^\$]*\)\${\([^}]*\)}\(.*\)/\2/")
            rest=$(echo "$line" | sed "s/\([^\$]*\)\${\([^}]*\)}\(.*\)/\3/")

            # .file.property
            if [[ "$var" == "."* ]]; then
                if [[ "${var:1}" == *"."* ]]; then
                    file=$(echo "${var}" | sed "s/^\(.[^.]*\).*$/\1/")
                    var=$(echo "${var}" | sed "s/^\(.[^.]*\)\.\(.*\)$/\2/")
                    var=$(cat "${file}" | grep "^${var}=" | sed "s/^[^=]*=//")
                else
                    var=$(cat "${var}")
                fi
            else
                # var == end var name
                var="${!var}"
            fi

            line="$pre$var$rest"
        done
        echo "$line" >> "${TMPFILE}"
    done

    echo "> ${file}"
	if [[ "$CMD" == "apply" ]]; then
        kubectl apply -f "${TMPFILE}"
	else
	    kubectl patch $OBJECT --type=json -p "$(cat ${TMPFILE})"
	fi
    rm -f "${TMPFILE}"
done
