#!/bin/bash

source .demoscript
# SKIP=1

# Usage: mkcluster cluster-name
# Creates 3 worker-node cluster in IBM Cloud to be used for a Knative demo

set -e

ZONE=${ZONE:-dal13}
MACHINE=${MACHINE:-b2c.4x16}
WORKERS=${WORKERS:-3}
NAME=${1:-kndemo}

comment "Checking to see if the cluster '%{NAME}' already exists..."
if ic ks clusters | grep "^${NAME} .* normal " > /dev/null 2>&1 ; then
    echo Cluster already exists
else
    comment Creating ${NAME}
    
    comment Get our VLAN info
    doit ic ks vlans --zone $ZONE
    PRI_VLAN=$(grep private out | sed "s/ .*//")
    PUB_VLAN=$(grep public out | sed "s/ .*//")
    
    comment Create the cluster
    doit echo ic ks cluster-create --name ${NAME} --zone ${ZONE} \
        --machine-type ${MACHINE} \
        --workers ${WORKERS} --private-vlan ${PRI_VLAN} \
        --public-vlan ${PUB_VLAN} \
        --kube-version $(ic ks kube-versions -s | tail -1)
    
    comment Wait for the cluster to be ready
    while ! (ic ks clusters | tee tmpout | grep "^${NAME} " | grep " normal "); do
        grep "^${NAME} " tmpout || true
        sleep 30
    done
    rm tmpout
fi

comment Get the KUBECONFIG export to use
ic config --check-version false
doit ic ks cluster-config -s --export ${NAME}
config=$(cat out)
$(${config})

comment Checking for Knative
if ! kubectl get ns knative-serving > /dev/null 2>&1 ; then
    comment "Install Knative (and Istio)"
    doit ibmcloud ks cluster-addon-enable knative -y --cluster ${NAME}

    comment "Wait until Knative is ready..."
    wait "kubectl get ns | grep knative-serving"
    comment "Knative namespace is there, now waiting for pods..."

    wait "kubectl get pods -n knative-serving | grep controller"
    wait ! "kubectl get pods --namespace knative-serving | \
        grep -v Terminating | grep -v NAME | grep -v Running"
else
    comment Knative is already installed
fi

comment Please run the following command to access the cluster:
echo ${config}
echo
