#!/bin/bash

(
kubectl get --no-headers endpoints | sed "s/^/endpoint\//"
kubectl get --no-headers all
) | sed "s/\s.*//g" | sort -u > out2

if [[ "$1" == "all" ]]; then
    grep -v knative.dev out2
	echo
fi

grep knative.dev out2
rm -f out2
