apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  generateName: build-hello
spec:
  serviceAccount: build-bot
  taskSpec:
    inputs:
      resources:
      - name: source
        type: git

    steps:
    - name: build-and-push
      workingdir: /workspace/source
      image: gcr.io/kaniko-project/executor:v0.9.0
      env:
      - name: DOCKER_CONFIG
        value: /builder/home/.docker
      command:
      - /kaniko/executor
      - --dockerfile=./Dockerfile
      - --context=/workspace/source/
      - --destination=index.docker.io/${APP_IMAGE}
    - name: trigger-service
      workingdir: /workspace/source
      image: duglin/curl
      command:
      - /usr/bin/curl
      - -X
      - POST
      - ${REBUILDURL}
      - -H
      - ce-type:newimage
      - -d
      - "{}"

  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/${GITREPO}

